# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
nome = input()
salarioFixo = float(input())
vendasEfetuadas = float(input())
salario = salarioFixo + vendasEfetuadas * 0.15
print("TOTAL = R$ %.2f"% salario)