# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
distancia = int(input())
gasto = float(input())  
consumo = distancia / gasto
print("%.3f km/l"% consumo)