# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
a, b, c = map(int, input().split(" "))
abs = (a - b) if (a - b) >= 0 else (-1) * (a - b)  
maiorAB = (a + b + abs)/2
abs = (maiorAB - c) if (maiorAB - c) >= 0 else (-1) * (maiorAB - c)
maiorABC = (maiorAB + c + abs)/2 
print("%i eh o maior"% maiorABC)