# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
segundos = int(input())
horas = segundos // 3600
segundos = segundos % 3600
minutos = segundos // 60
segundos = segundos % 60
print('{}:{}:{}'.format(horas, minutos, segundos))