# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
a, b, c = map(float, input().split(" "))
areaTriangulo = a * c / 2
areaCirculo = 3.14159 * c**2
areaTrapezio = (a + b) * c / 2
areaQuadrado = b**2
areaRetangulo = a * b
print("TRIANGULO: %.3f"% areaTriangulo)
print("CIRCULO: %.3f"% areaCirculo)
print("TRAPEZIO: %.3f"% areaTrapezio)
print("QUADRADO: %.3f"% areaQuadrado)
print("RETANGULO: %.3f"% areaRetangulo)