# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
a = float(input()) * 3.5
b = float(input()) * 7.5
media = (a + b) / 11
print("MEDIA = %.5f"% media)