# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
salario = float(input())
if salario <= 2000:
  print("Isento")
elif salario <= 3000:
  imposto = (salario - 2000) * 0.08
  print("R$ %.2f"% imposto)
elif salario <= 4500:
  imposto = ((salario - 3000) * 0.18) + 80
  print("R$ %.2f"% imposto)
else:
  imposto = ((salario - 4500) * 0.28) + 350
  print("R$ %.2f"% imposto)