# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
numero = int(input())
horas = int(input())
valorHora = float(input())
salario = (horas * valorHora)
print("NUMBER = %i"% numero)
print("SALARY = U$ %.2f"% salario)