# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""
def achaM(valor, m):
  vet = []
  for x in range(valor):
    vet.append(x + 1)
  index = 0
  if len(vet) > 1:
    while True:
      vet.remove(vet[0 + index])
      index = (index - 1 + m) % len(vet)
      if not len(vet) > 1:
        break
  return vet[0] == 13
valor = -1
valores = []
while valor != 0:
  valor = int(input())
  m = 1
  if valor != 0:
    while not achaM(valor, m):
      m+=1

  valores.append(m) if valor != 0 else ""
for x in valores:
  print(x)