# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
valor = int(input())
cem = valor / 100
resto = valor % 100
cinquenta = resto / 50
resto = resto % 50
vinte = resto / 20
resto = resto % 20
dez = resto / 10
resto = resto % 10
cinco = resto / 5
resto = resto % 5
dois = resto / 2
um = resto % 2
print("%i"% valor)
print("%i nota(s) de R$ 100,00"% cem)
print("%i nota(s) de R$ 50,00"% cinquenta)
print("%i nota(s) de R$ 20,00"% vinte)
print("%i nota(s) de R$ 10,00"% dez)
print("%i nota(s) de R$ 5,00"% cinco)
print("%i nota(s) de R$ 2,00"% dois)
print("%i nota(s) de R$ 1,00"% um)