# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
a = int(input())
b = int(input())
c = int(input())
d = int(input())
dif = (a * b - c * d)
print("DIFERENCA = %i"% dif)