# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
raio = float(input())
volume = (4.0 / 3) * 3.14159 * raio**3
print("VOLUME = %.3f"% volume)