# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
import math

x1, y1 = map(float, input().split(" "))
x2, y2 = map(float, input().split(" "))  
distancia = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print("%.4f"% distancia)