# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
valores1 = input().split(" ")
valores2 = input().split(" ")
codigo1, quantidade1, valor1 = valores1
codigo2, quantidade2, valor2 = valores2 
total = (float(valor1) * int(quantidade1)) + (float(valor2) * int(quantidade2))
print("VALOR A PAGAR: R$ %.2f"% total)