# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
tabela = [4.00, 4.50, 5.00, 2.00, 1.50]
codigo, quantidade = map(int, input().split(" "))
total = quantidade * tabela[codigo - 1]
print("Total: R$ %.2f"% total)