# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12NSHlmvdlPV0utRJ4OyewO7hH4nN4nnk
"""

# -*- coding: utf-8 -*-
def verificaNo(index, soma, n, f, positivo, negativo, transacoes, memoria):

  if index >= n and soma == f:
    return True
  elif index >= n:
    return False
  if (soma, index) in memoria:
    return memoria[soma, index]

  ent = False
  said = False
  ent = verificaNo(index + 1, soma + transacoes[index], n, f, positivo, negativo, transacoes, memoria)
  said = verificaNo(index + 1, soma - transacoes[index], n, f, positivo, negativo, transacoes, memoria)
  
  if ent == True and said == False:
    positivo[index] = True
  elif ent == False and said == True:
    negativo[index] = True
  elif ent == True and said == True:
    positivo[index] = negativo[index] = True
  memoria[soma, index] = ent or said
  return memoria[soma, index]

resultados = []
entrada = input()
while entrada != "0 0":
  positivo = []
  negativo = []
  transacoes = []
  memoria = {}
  n, f = map(int, entrada.split(" "))
  for x in range(n):
    positivo.append(False)
    negativo.append(False)
    transacoes.append(int(input()))
  valido = verificaNo(0, 0, n, f, positivo, negativo, transacoes, memoria)
  if valido:
    resultado = ""
    for x in range(n):
      if positivo[x] and negativo[x]:
        resultado += "?"
      elif positivo[x]:
        resultado += "+"
      else:
        resultado += "-"
    resultados.append(resultado)
  else:
    resultados.append("*")
  entrada = input()
for x in resultados:
  print(x)