# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrqoKxE2geLL9KeyTCkKucjLk2TngL8r
"""

# -*- coding: utf-8 -*-
a = float(input()) * 2
b = float(input()) * 3
c = float(input()) * 5
media = (a + b + c) / 10
print("MEDIA = %.1f"% media)